dist: trusty
language: python
cache:
    packages: true
    directories:
        - $HOME/.keras
        - $HOME/.cache/pip

matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=tensorflow TEST_MODE=PEP8
        - python: 2.7
          env: KERAS_BACKEND=tensorflow
        - python: 3.5
          env: KERAS_BACKEND=tensorflow
        - python: 3.6
          env: KERAS_BACKEND=tensorflow

install:
    - pip install pytest-pep8 pytest-cov

    - pip install --upgrade pytest

    # install TensorFlow
    - pip install tensorflow

    # install package locally
    - pip install .[full]

    # download spacy model
    - "python -m spacy download en"

script:
    # run keras backend init to initialize backend config
    - python -c "import keras.backend"
    # set up keras backend
    - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
    - echo -e "Running tests with the following config:\n$(cat ~/.keras/keras.json)"
    - if [[ "$TEST_MODE" == "PEP8" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH pytest --pep8 -m pep8;
      else
      PYTHONPATH=$PWD:$PYTHONPATH/tests pytest tests/*;
      fi

notifications:
    email: false
